name: Pester Tests
on:
  push:
    paths:
      - '**.ps1'
      - '.github/workflows/pester.yml'
      - 'tests/**'
  pull_request:
    paths:
      - '**.ps1'
      - '.github/workflows/pester.yml'
      - 'tests/**'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Print PowerShell version
        shell: pwsh
        run: |
          $PSVersionTable
          
      - name: Install Pester 5.7.1
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -RequiredVersion 5.7.1 -Scope CurrentUser
          
      - name: Verify Pester installation
        shell: pwsh
        run: |
          Get-Module -ListAvailable Pester | Format-Table Name,Version,Path
          
      - name: Run Pester tests with coverage
        shell: pwsh
        run: |
          # Import the installed Pester module
          Import-Module Pester -RequiredVersion 5.7.1 -Force
          
          # Configure Pester
          $config = New-PesterConfiguration
          $config.Run.Path = 'tests'
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.Path = 'cert-exporter.ps1'
          $config.Output.Verbosity = 'Detailed'
          
          # Run tests
          $res = Invoke-Pester -Configuration $config -PassThru
          
          # Report results
          Write-Host "Tests Passed: $($res.PassedCount)"
          Write-Host "Tests Failed: $($res.FailedCount)"
          
          # Report coverage if available
          if ($res.CodeCoverage) {
            Write-Host "Coverage %: $($res.CodeCoverage.CoveragePercent)"
            
            # Fail if coverage is below threshold
            if ($res.CodeCoverage.CoveragePercent -lt 80) { 
              Write-Error "Code coverage below threshold (80%)"
              exit 1 
            }
          }
          
          # Fail if any tests failed
          if ($res.FailedCount -gt 0) { 
            Write-Error "Tests failed"
            exit 1 
          }