name: Pester Tests

on:
  push:
    paths:
      - '**.ps1'
      - '.github/workflows/pester.yml'
      - 'tests/**'
  pull_request:
    paths:
      - '**.ps1'
      - '.github/workflows/pester.yml'
      - 'tests/**'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List all available Pester versions and paths
        shell: pwsh
        run: |
          Get-Module -ListAvailable Pester | Format-Table Name,Version,Path

      - name: Print PSModulePath and USERPROFILE
        shell: pwsh
        run: |
          Write-Host "PSModulePath: $env:PSModulePath"
          Write-Host "USERPROFILE: $env:USERPROFILE"

      - name: Import Pester 5.7.1 by path
        shell: pwsh
        run: |
          Import-Module 'C:\Program Files\WindowsPowerShell\Modules\Pester\5.7.1\Pester.psd1' -Force
          Write-Host "Imported Pester 5.7.1"
          Get-Module Pester | Format-List

      - name: Run Pester tests with coverage
        shell: pwsh
        run: |
          Import-Module 'C:\Program Files\WindowsPowerShell\Modules\Pester\5.7.1\Pester.psd1' -Force
          $config = New-PesterConfiguration
          $config.Run.Path = 'tests'
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.Path = 'cert-exporter.ps1'
          $config.Output.Verbosity = 'Detailed'
          $res = Invoke-Pester -Configuration $config -PassThru
          Write-Host "Coverage %: $($res.CodeCoverage.Percent)"
          if ($res.CodeCoverage.Percent -lt 80) { exit 1 }
