name: Pester Tests
on:
  push:
    paths:
      - '**.ps1'
      - '.github/workflows/pester.yml'
      - 'tests/**'
  pull_request:
    paths:
      - '**.ps1'
      - '.github/workflows/pester.yml'
      - 'tests/**'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Print PowerShell version
        shell: pwsh
        run: |
          $PSVersionTable
          
      - name: Install Pester 5.7.1
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -RequiredVersion 5.7.1 -Scope CurrentUser
          
      - name: Verify Pester installation
        shell: pwsh
        run: |
          Get-Module -ListAvailable Pester | Format-Table Name,Version,Path
          
      - name: Confirm loaded Pester version and type
        shell: pwsh
        run: |
          $env:PSModulePath = "$HOME/.local/share/powershell/Modules:" + $env:PSModulePath
          Import-Module Pester -RequiredVersion 5.7.1 -Force
          Get-Module Pester | Format-List Name,Version,Path
          [PesterConfiguration]::Default

      - name: Run Pester tests with coverage
        shell: pwsh
        run: |
          $env:PSModulePath = "$HOME/.local/share/powershell/Modules:" + $env:PSModulePath
          Import-Module Pester -RequiredVersion 5.7.1 -Force
          Get-Module Pester | Format-List Name,Version,Path
          $config = [PesterConfiguration]::Default
          $config.Run.Path = 'tests'
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.Path = 'cert-exporter.ps1'
          $config.Output.Verbosity = 'Detailed'
          $res = Invoke-Pester -Configuration $config
          Write-Host "Tests Passed: $($res.PassedCount)"
          Write-Host "Tests Failed: $($res.FailedCount)"
          if ($null -ne $res.CodeCoverage) {
            $coveragePercent = [math]::Round(($res.CodeCoverage.CommandsExecutedCount / $res.CodeCoverage.CommandsAnalyzedCount) * 100, 2)
            Write-Host "Coverage %: $coveragePercent"
            if ($coveragePercent -lt 80) { 
              Write-Error "Code coverage below threshold (80%)"
              exit 1 
            }
          }
          if ($res.FailedCount -gt 0) { 
            Write-Error "Tests failed"
            exit 1 
          }